/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ajpham.appchatclient.gui.linegui;

import com.ajpham.appchatclient.dto.ChannelDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author taipham
 */
public class InforLine extends javax.swing.JPanel implements ListCellRenderer<ChannelDTO>{

    /**
     * Creates new form InforLineGUI
     */
    public InforLine() {
        initComponents();
        this.lbMessWait.setVisible(false);
    }

      public void SetPicture(JLabel label, byte[] avatar) {
        if (avatar != null) {
            Image img = new ImageIcon(avatar).getImage()
                    .getScaledInstance(67, 67, BufferedImage.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            label.setIcon(icon);  
        }
    }
    
    public void SetName(String name){
        lbChannelName.setText(name);
    }
    
    public void SetNumberOfMessWait(int number){
        lbMessWait.setText(String.valueOf(number));
    }
    
    public JLabel GetLbAvatar(){
        return this.lbAvatar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMessWait = new javax.swing.JLabel();
        lbChannelName = new javax.swing.JLabel();
        lbAvatar = new javax.swing.JLabel();
        lbListMembers = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(332, 79));

        lbMessWait.setBackground(new java.awt.Color(255, 0, 51));
        lbMessWait.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbMessWait.setForeground(new java.awt.Color(255, 255, 255));
        lbMessWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessWait.setOpaque(true);

        lbChannelName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbChannelName.setForeground(new java.awt.Color(0, 0, 0));
        lbChannelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbChannelName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lbAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbListMembers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbChannelName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbListMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMessWait, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbChannelName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbListMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMessWait, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbChannelName;
    private javax.swing.JLabel lbListMembers;
    private javax.swing.JLabel lbMessWait;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends ChannelDTO> list, ChannelDTO value, int index, boolean isSelected, boolean cellHasFocus) {
        this.SetPicture(this.lbAvatar, value.getAvatar());
        this.lbChannelName.setText(value.getChannelName());
        this.lbMessWait.setText(String.valueOf(10));
        this.lbListMembers.setText(value.getListMembers());
        
        this.lbAvatar.setOpaque(true);
        this.lbChannelName.setOpaque(true);
        this.lbListMembers.setOpaque(true);
        
        // when select item
        if (isSelected) {
            this.lbAvatar.setBackground(list.getSelectionBackground());
            this.lbChannelName.setBackground(new Color(193, 238, 255));
//            this.lbMessWait.setBackground(list.getSelectionBackground());
            this.lbListMembers.setBackground(new Color(193, 238, 255));
            setBackground(new Color(193, 238, 255));
        } else { // when don't select
            this.lbAvatar.setBackground(list.getBackground());
            this.lbChannelName.setBackground(list.getBackground());
//            this.lbMessWait.setBackground(list.getBackground());
            this.lbListMembers.setBackground(list.getBackground());
            setBackground(list.getBackground());
        }
        return this;
    }
    
    
}
