/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ajpham.appchatclient.gui.clientgui;

import com.ajpham.appchatclient.bus.ChannelBUS;
import com.ajpham.appchatclient.dto.RequestDTO;
import com.ajpham.appchatclient.nettyclient.NettyClient;
import com.ajpham.appchatclient.service.ServiceChannel;
import com.ajpham.appchatclient.service.ServiceUser;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author taipham
 */
public class CreateRoomFormGUI extends javax.swing.JDialog {

    /**
     * Creates new form CreateRoomFormGUI
     */
    private HandleAvatar _handleAvatar;
    private String _pathFileAvatar = "Choose Avatar";
    private RequestDTO.Request _msgRequest;
    private ChannelBUS _roomBUS;
    private List<String> _listMembers = new ArrayList<>();
    private RequestDTO.Channel _channel;
    private static NettyClient _nettyClient;
    private static String _token;
    private static ServiceUser _serviceUser;
    private static ServiceChannel _serviceChannel;

    public CreateRoomFormGUI(java.awt.Frame parent, boolean modal, NettyClient nettyClient, String token) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        _nettyClient = nettyClient;
        _token = token;
        _nettyClient.getHandler().setCreateRoomGUI(this);
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbAvatar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfRoomname = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tfFindMember = new javax.swing.JTextField();
        lbFind = new javax.swing.JLabel();
        tfMembers = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbStatusFind = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Room");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        lbAvatar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbAvatar.setForeground(java.awt.Color.gray);
        lbAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar.setText("Choose Avatar");
        lbAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAvatarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbAvatarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbAvatarMouseEntered(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Roomname:");

        tfRoomname.setBackground(new java.awt.Color(255, 255, 255));
        tfRoomname.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tfRoomname.setForeground(new java.awt.Color(0, 0, 0));
        tfRoomname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRoomnameKeyPressed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tfFindMember.setBackground(new java.awt.Color(255, 255, 255));
        tfFindMember.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tfFindMember.setForeground(new java.awt.Color(0, 0, 0));
        tfFindMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFindMemberKeyPressed(evt);
            }
        });

        lbFind.setBackground(new java.awt.Color(255, 255, 255));
        lbFind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsearch.png"))); // NOI18N
        lbFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFindMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbFindMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbFindMouseEntered(evt);
            }
        });

        tfMembers.setBackground(new java.awt.Color(255, 255, 255));
        tfMembers.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tfMembers.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Members:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Find member:");

        lbStatusFind.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbStatusFind.setForeground(new java.awt.Color(255, 51, 0));
        lbStatusFind.setText("Not Found");

        lbStatus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 51, 0));
        lbStatus.setText("Create Room Faile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCancel)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnCreate))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfFindMember, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfRoomname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbFind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addComponent(lbStatusFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfFindMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(lbFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStatusFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfRoomname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnCreate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        _handleAvatar = new HandleAvatar();
        _serviceUser = new ServiceUser(_nettyClient.getHandler());
        _serviceChannel = new ServiceChannel(_nettyClient.getHandler());
        this._roomBUS = new ChannelBUS();
        this.lbStatus.setVisible(false);
        this.lbStatusFind.setVisible(false);
        this.tfMembers.setEnabled(false);
    }

    //set image
    public void setPicture(JLabel label, byte[] avatar) {
        if (avatar != null) {
            Image img = new ImageIcon(avatar).getImage().
                    getScaledInstance(lbAvatar.getSize().width, lbAvatar.getSize().height, BufferedImage.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lbAvatar.setIcon(icon);
            lbAvatar.setText("");
        } else {
            lbAvatar.setText("Choose Avatar");
        }
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure to close Create Room form?", "Really Closing?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lbAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvatarMouseClicked
        _pathFileAvatar = _handleAvatar.chooseAvatar();
        byte[] avatar;
        try {
            avatar = _handleAvatar.convertFile(_pathFileAvatar);
            setPicture(lbAvatar, avatar);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lbAvatarMouseClicked

    private void lbAvatarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvatarMouseEntered
        lbAvatar.setForeground(Color.RED);
    }//GEN-LAST:event_lbAvatarMouseEntered

    private void lbAvatarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvatarMouseExited
        lbAvatar.setForeground(Color.GRAY);
    }//GEN-LAST:event_lbAvatarMouseExited

    private void lbFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFindMouseClicked
        String nameMember = this.tfFindMember.getText().trim();
        if (!nameMember.equals("") && !nameMember.equals(_nettyClient.getUserName())) {
            //send message to server
            _serviceUser.sendMessageFindUser(_token, nameMember);
        }
    }//GEN-LAST:event_lbFindMouseClicked

    private void tfFindMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFindMemberKeyPressed
        if (this.tfFindMember.getText().equals("")) {
            this.lbStatusFind.setVisible(false);
            this.lbStatus.setVisible(false);
        }
    }//GEN-LAST:event_tfFindMemberKeyPressed

    private void lbFindMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFindMouseEntered
        Border border = BorderFactory.createLineBorder(Color.GRAY, 2);
        lbFind.setBorder(border);
    }//GEN-LAST:event_lbFindMouseEntered

    private void lbFindMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFindMouseExited
        Border border = BorderFactory.createEmptyBorder();
        lbFind.setBorder(border);
    }//GEN-LAST:event_lbFindMouseExited

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String listMembers = this.tfMembers.getText().trim();
        String channelName = this.tfRoomname.getText().trim();
        if (!this._roomBUS.checkRoomCreate(listMembers, channelName, _pathFileAvatar)) {
            this.lbStatus.setVisible(true);
        } else {
            try {
                listMembers = this.tfMembers.getText() + ", " + _nettyClient.getUserName();
                _serviceChannel.sendMessageCreateChannel(_token, _nettyClient.getUserName(), channelName, _handleAvatar.convertFile(_pathFileAvatar), listMembers);
            } catch (IOException ex) {
                Logger.getLogger(CreateRoomFormGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void tfRoomnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRoomnameKeyPressed
        if (this.tfRoomname.getText().equals("")) {
            this.lbStatus.setVisible(false);
        }
    }//GEN-LAST:event_tfRoomnameKeyPressed

    public void setStatusFind(String status) {
        this.lbStatusFind.setText(status);
        this.lbStatusFind.setVisible(true);
        if (status.equals("Find")) {
            this.tfFindMember.setText("");
        }
    }

    public void setStatus(String status) {
        this.lbStatus.setText(status);
        this.lbStatus.setVisible(true);
    }

    public void setTfMembers(String member) {
        String members = tfMembers.getText();
        if (!_listMembers.contains(member)) {
            this._listMembers.add(member);
            if (members.equals("")) {
                this.tfMembers.setText(member);
            } else {
                this.tfMembers.setText(this.tfMembers.getText() + ", " + member);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRoomFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRoomFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRoomFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRoomFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateRoomFormGUI dialog = new CreateRoomFormGUI(new javax.swing.JFrame(), true, _nettyClient, _token);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbFind;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbStatusFind;
    private javax.swing.JTextField tfFindMember;
    private javax.swing.JTextField tfMembers;
    private javax.swing.JTextField tfRoomname;
    // End of variables declaration//GEN-END:variables
}
